package analyze

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/plaesy/spec-kit/internal/common"
)

// analysisFixture is a small but complete Go project: source, docs, a test
// directory and a CI workflow (which lives under a dot directory and is
// therefore excluded from the walk).
func analysisFixture(t *testing.T) string {
	t.Helper()
	return newFixture(t, map[string]string{
		"go.mod":                   "module example.com/app\n\ngo 1.22\n",
		"main.go":                  "package main\n\nfunc main() {}\n",
		"README.md":                "# app\n",
		"docs/guide.md":            "# guide\n",
		"docs/api.md":              "# api\n",
		"docs/adr/0001-init.md":    "# adr\n",
		"tests/app_test.go":        "package main\n",
		".github/workflows/ci.yml": "on: push\n",
	})
}

const analysisDirName = ".plaesy/analysis"

func TestFileNames(t *testing.T) {
	cases := []struct {
		name  string
		files []fileInfo
		want  []string
	}{
		{"empty", nil, []string{}},
		{"single", files("main.go"), []string{"main.go"}},
		{"nested", files("a/b/c.go", "a/d.go"), []string{"a/b/c.go", "a/d.go"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := fileNames(tc.files); !equalStrings(got, tc.want) {
				t.Errorf("fileNames() = %v, want %v", got, tc.want)
			}
		})
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func TestTrimVersion(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"empty", "", ""},
		{"clean", "1.2.3", "1.2.3"},
		{"trailing newline", "1.2.3\n", "1.2.3"},
		{"trailing crlf", "1.2.3\r\n", "1.2.3"},
		{"trailing space", "1.2.3 ", "1.2.3"},
		{"mixed trailing whitespace", "1.2.3\n\n  \r", "1.2.3"},
		{"leading whitespace is preserved", " 1.2.3\n", " 1.2.3"},
		{"inner whitespace is preserved", "1.2.3 v2\n", "1.2.3 v2"},
		{"whitespace only", "\n\r ", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := trimVersion(tc.in); got != tc.want {
				t.Errorf("trimVersion(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestFrameworkVersionFor(t *testing.T) {
	orig := common.Version
	t.Cleanup(func() { common.Version = orig })

	t.Run("ldflags version wins", func(t *testing.T) {
		common.Version = "3.4.5"
		if got := frameworkVersionFor(t.TempDir()); got != "3.4.5" {
			t.Errorf("frameworkVersionFor() = %q, want 3.4.5", got)
		}
	})

	// With no injected version the analyzer falls back to a VERSION file two
	// directories above the running executable, then to the "0.0.1" default.
	for _, injected := range []string{"", "0.0.0"} {
		t.Run("fallback for version "+quote(injected), func(t *testing.T) {
			common.Version = injected
			want := "0.0.1"
			if exe, err := os.Executable(); err == nil {
				candidate := filepath.Join(filepath.Dir(exe), "..", "..", "VERSION")
				if data, err := os.ReadFile(candidate); err == nil {
					want = trimVersion(string(data))
				}
			}
			got := frameworkVersionFor(t.TempDir())
			if got != want {
				t.Errorf("frameworkVersionFor() = %q, want %q", got, want)
			}
			if got == "" {
				t.Error("frameworkVersionFor must never return an empty version")
			}
		})
	}
}

func quote(s string) string { return "\"" + s + "\"" }

func TestRunGeneratesAnalysisArtifacts(t *testing.T) {
	logs := captureLogs(t)
	project := analysisFixture(t)

	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("Run: %v", err)
	}

	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	for _, name := range []string{"project.json", "project.structure.json", "overview.md", ".analysis-fingerprint"} {
		if _, err := os.Stat(filepath.Join(analysisDir, name)); err != nil {
			t.Errorf("expected %s to be generated: %v", name, err)
		}
	}
	if info, err := os.Stat(filepath.Join(project, ".plaesy", "memory")); err != nil || !info.IsDir() {
		t.Errorf("expected .plaesy/memory to be created, err=%v", err)
	}
	// NoGraph means no graph artifacts.
	for _, name := range []string{"project.graph.json", "project.html", "reports.md"} {
		if _, err := os.Stat(filepath.Join(analysisDir, name)); !os.IsNotExist(err) {
			t.Errorf("NoGraph should not produce %s (err=%v)", name, err)
		}
	}

	out := logs.joined()
	mustContain(t, out, "Starting comprehensive project analysis...")
	mustContain(t, out, "Analysis directory: "+analysisDir)
	mustContain(t, out, "[SUCCESS] Comprehensive project.json generated")
	mustContain(t, out, "[SUCCESS] Comprehensive analysis completed!")
	mustContain(t, out, "No topic memory files are generated by analyze.")
	mustNotContain(t, out, "project.graph.json")

	pj := readFileString(t, filepath.Join(analysisDir, "project.json"))
	mustContain(t, pj, `"type": "go"`)
	mustContain(t, pj, `"confidence": "medium"`)
	// 7 walked files: the .github workflow lives in an excluded dot directory.
	mustContain(t, pj, `"total_files": 7`)
	mustContain(t, pj, `"primary_languages": [`)
	mustContain(t, pj, "Go")
	mustContain(t, pj, `"generated_by": "Plaesy Spec-Kit v`)

	overview := readFileString(t, filepath.Join(analysisDir, "overview.md"))
	mustContain(t, overview, "# Project Analysis Overview")
	mustContain(t, overview, "| Source Code | 2 |")   // main.go + tests/app_test.go
	mustContain(t, overview, "| Documentation | 4 |") // README + 3 docs markdown files
	mustContain(t, overview, "| Config | 0 |")        // go.mod is not classified (".mod" is not a config extension)
	mustContain(t, overview, "No gaps detected against baseline checks (docs, tests, CI)")
	mustContain(t, overview, "- **Framework**: go")
}

func TestRunSkipsRegenerationWhenUnchanged(t *testing.T) {
	project := analysisFixture(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	overviewPath := filepath.Join(analysisDir, "overview.md")
	const sentinel = "SENTINEL-MUST-NOT-BE-REGENERATED"
	if err := os.WriteFile(overviewPath, []byte(sentinel), 0o644); err != nil {
		t.Fatalf("seed sentinel: %v", err)
	}

	logs := captureLogs(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	if got := readFileString(t, overviewPath); got != sentinel {
		t.Errorf("overview.md was regenerated on an unchanged project:\n%s", got)
	}
	out := logs.joined()
	mustContain(t, out, "Analysis unchanged since last run. Skipping regeneration (use --force to override).")
	mustContain(t, out, "overview.md - Analysis snapshot (cached)")
	mustNotContain(t, out, "Comprehensive analysis completed!")
}

func TestRunForceRegeneratesDespiteUnchangedFingerprint(t *testing.T) {
	project := analysisFixture(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	overviewPath := filepath.Join(analysisDir, "overview.md")
	const sentinel = "SENTINEL"
	if err := os.WriteFile(overviewPath, []byte(sentinel), 0o644); err != nil {
		t.Fatalf("seed sentinel: %v", err)
	}

	logs := captureLogs(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true, Force: true}); err != nil {
		t.Fatalf("forced Run: %v", err)
	}
	got := readFileString(t, overviewPath)
	if strings.Contains(got, sentinel) {
		t.Error("--force must regenerate even when the fingerprint matches")
	}
	mustContain(t, got, "# Project Analysis Overview")
	mustNotContain(t, logs.joined(), "Skipping regeneration")
}

func TestRunRegeneratesAfterAProjectChange(t *testing.T) {
	project := analysisFixture(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	overviewPath := filepath.Join(analysisDir, "overview.md")
	const sentinel = "SENTINEL"
	if err := os.WriteFile(overviewPath, []byte(sentinel), 0o644); err != nil {
		t.Fatalf("seed sentinel: %v", err)
	}

	if err := os.WriteFile(filepath.Join(project, "new_module.go"), []byte("package main\n"), 0o644); err != nil {
		t.Fatalf("add source file: %v", err)
	}
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	got := readFileString(t, overviewPath)
	if strings.Contains(got, sentinel) {
		t.Error("adding a tracked source file must invalidate the fingerprint")
	}
	mustContain(t, got, "| Source Code | 3 |") // the new_module.go from this test
}

func TestRunProjectPathVariants(t *testing.T) {
	cases := []struct {
		name    string
		suffix  string
		wantDir string
	}{
		{"plain path", "", ""},
		{"trailing separator", string(os.PathSeparator), ""},
		{"trailing dot", string(os.PathSeparator) + ".", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			captureLogs(t)
			project := analysisFixture(t)
			if err := Run(Options{ProjectPath: project + tc.suffix, NoGraph: true}); err != nil {
				t.Fatalf("Run: %v", err)
			}
			analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
			if _, err := os.Stat(analysisDir); err != nil {
				t.Fatalf("analysis dir not created at %s: %v", analysisDir, err)
			}
			pj := readFileString(t, filepath.Join(analysisDir, "project.json"))
			mustContain(t, pj, `"name": "`+filepath.Base(project)+`"`)
		})
	}
}

func TestRunDefaultsToWorkingDirectory(t *testing.T) {
	project := t.TempDir()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	// Registered after t.TempDir so it runs first (cleanups are LIFO).
	t.Cleanup(func() {
		if err := os.Chdir(wd); err != nil {
			t.Fatalf("restore wd: %v", err)
		}
	})
	if err := os.Chdir(project); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	captureLogs(t)

	if err := Run(Options{NoGraph: true}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	if _, err := os.Stat(filepath.Join(analysisDir, "project.json")); err != nil {
		t.Errorf("expected project.json in the working directory: %v", err)
	}
}

func TestRunWithGraphEnabled(t *testing.T) {
	logs := captureLogs(t)
	project := analysisFixture(t)
	if err := Run(Options{ProjectPath: project}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	for _, name := range []string{"project.graph.json", "project.html", "reports.md", ".fingerprint"} {
		if _, err := os.Stat(filepath.Join(analysisDir, name)); err != nil {
			t.Errorf("expected graph artifact %s: %v", name, err)
		}
	}
	out := logs.joined()
	mustContain(t, out, "Building dependency graph (incremental: only rebuilds if source changed)...")
	mustContain(t, out, "- project.graph.json - Dependency graph (nodes + edges)")

	// A forced run announces the forced path.
	forced := captureLogs(t)
	if err := Run(Options{ProjectPath: project, Force: true}); err != nil {
		t.Fatalf("forced Run: %v", err)
	}
	mustContain(t, forced.joined(), "Building dependency graph (forced)...")
}

func TestRunSurvivesGraphFailure(t *testing.T) {
	logs := captureLogs(t)
	// An empty project has no source files, so graph.Build fails; the summary
	// artifacts must still be produced and the error must be logged, not fatal.
	project := newFixture(t, map[string]string{"notes.untracked": "x"})
	if err := Run(Options{ProjectPath: project}); err != nil {
		t.Fatalf("Run must not fail when the graph build fails: %v", err)
	}
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	if _, err := os.Stat(filepath.Join(analysisDir, "project.json")); err != nil {
		t.Errorf("project.json should still be generated: %v", err)
	}
	out := logs.joined()
	mustContain(t, out, "Graph build skipped/failed; summary files remain valid.")

	// A run whose graph build failed must not leave a fingerprint behind. The
	// fingerprint is the claim that every listed artifact exists, and the fast
	// path above trusts it: with one recorded, the *next* run took the skip
	// path, printed the three missing graph files as "(cached)", and never
	// built the graph again without --force. The failure was announced once
	// and then cached away.
	if _, err := os.Stat(filepath.Join(analysisDir, ".analysis-fingerprint")); !os.IsNotExist(err) {
		t.Errorf("a failed graph build must not record the analysis fingerprint (stat err=%v)", err)
	}
	// Same reason: "Generated files" is a list of what is on disk, not of
	// what the flags asked for.
	mustNotContain(t, out, "project.graph.json - Dependency graph")
	mustNotContain(t, out, "project.html - Interactive graph visualization")
	mustNotContain(t, out, "reports.md - Graph report")
	mustContain(t, out, "Not recording the analysis fingerprint")

	// And the recovery path works: a second run on the same project must
	// regenerate rather than report the missing graph as cached.
	logs2 := captureLogs(t)
	if err := Run(Options{ProjectPath: project}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	mustNotContain(t, logs2.joined(), "Analysis unchanged since last run")
}

// With --no-graph there is no graph to fail, so the run is complete and the
// fingerprint is recorded — but the graph files must not be listed as
// generated, because they were never asked for and do not exist.
func TestRunWithNoGraphDoesNotListGraphArtifacts(t *testing.T) {
	logs := captureLogs(t)
	project := analysisFixture(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := logs.joined()
	mustNotContain(t, out, "project.graph.json - Dependency graph")
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
	if _, err := os.Stat(filepath.Join(analysisDir, ".analysis-fingerprint")); err != nil {
		t.Errorf("a --no-graph run still produced the summary artifacts, so it is complete: %v", err)
	}
}

func TestBuildGraph(t *testing.T) {
	project := newFixture(t, map[string]string{
		"README.md":        "# doc\n\nSee [main](main.go).\n",
		"main.go":          "package main\n",
		"internal/util.go": "package internal\n",
	})
	analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))

	if err := buildGraph(project, false); err != nil {
		t.Fatalf("buildGraph: %v", err)
	}
	graphPath := filepath.Join(analysisDir, "project.graph.json")
	for _, name := range []string{"project.graph.json", "project.html", "reports.md", ".fingerprint"} {
		if _, err := os.Stat(filepath.Join(analysisDir, name)); err != nil {
			t.Errorf("expected %s: %v", name, err)
		}
	}
	fp := readFileString(t, filepath.Join(analysisDir, ".fingerprint"))
	if strings.TrimSpace(fp) == "" {
		t.Error("expected a non-empty graph fingerprint")
	}

	// Second incremental build: unchanged sources, so the artifacts are left
	// untouched.
	const sentinel = "UNTOUCHED"
	if err := os.WriteFile(graphPath, []byte(sentinel), 0o644); err != nil {
		t.Fatalf("seed sentinel: %v", err)
	}
	if err := buildGraph(project, false); err != nil {
		t.Fatalf("second buildGraph: %v", err)
	}
	if got := readFileString(t, graphPath); got != sentinel {
		t.Error("incremental build should have skipped because the source fingerprint is unchanged")
	}

	// Forced build always regenerates.
	if err := buildGraph(project, true); err != nil {
		t.Fatalf("forced buildGraph: %v", err)
	}
	if got := readFileString(t, graphPath); got == sentinel {
		t.Error("forced build should have regenerated project.graph.json")
	}

	// A source change invalidates the incremental fingerprint.
	if err := os.WriteFile(filepath.Join(project, "added.go"), []byte("package main\n"), 0o644); err != nil {
		t.Fatalf("write added.go: %v", err)
	}
	if err := os.WriteFile(graphPath, []byte(sentinel), 0o644); err != nil {
		t.Fatalf("seed sentinel: %v", err)
	}
	if err := buildGraph(project, false); err != nil {
		t.Fatalf("third buildGraph: %v", err)
	}
	if got := readFileString(t, graphPath); got == sentinel {
		t.Error("a new source file must invalidate the incremental graph build")
	}
}

func TestBuildGraphReportsErrors(t *testing.T) {
	empty := t.TempDir()
	err := buildGraph(empty, false)
	if err == nil {
		t.Fatal("expected an error when there is nothing to graph")
	}
	if !strings.Contains(err.Error(), "building graph") {
		t.Errorf("error = %v, want it to mention the failing stage", err)
	}
}

// TestBuildGraphWriteErrors blocks each graph artifact by pre-creating a
// directory with that name, so the corresponding writer fails.
func TestBuildGraphWriteErrors(t *testing.T) {
	cases := []struct {
		name        string
		blocker     string
		wantErrPart string
	}{
		{"project.graph.json", "project.graph.json", "saving project.graph.json"},
		{"project.html", "project.html", "writing project.html"},
		{"reports.md", "reports.md", "writing reports.md"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			project := newFixture(t, map[string]string{
				"README.md": "# doc\n",
				"main.go":   "package main\n",
			})
			analysisDir := filepath.Join(project, filepath.FromSlash(analysisDirName))
			if err := os.MkdirAll(filepath.Join(analysisDir, tc.blocker), 0o755); err != nil {
				t.Fatalf("create blocker: %v", err)
			}
			err := buildGraph(project, false)
			if err == nil {
				t.Fatalf("expected an error when %s cannot be written", tc.blocker)
			}
			if !strings.Contains(err.Error(), tc.wantErrPart) {
				t.Errorf("error = %v, want it to mention %q", err, tc.wantErrPart)
			}
		})
	}
}

func TestRunDirectoryCreationErrors(t *testing.T) {
	cases := []struct {
		name        string
		files       map[string]string
		wantErrPart string
	}{
		{
			name:        "analysis dir blocked by a file",
			files:       map[string]string{".plaesy": "not a directory"},
			wantErrPart: "create analysis dir",
		},
		{
			name:        "memory dir blocked by a file",
			files:       map[string]string{".plaesy/memory": "not a directory"},
			wantErrPart: "create memory dir",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			captureLogs(t)
			project := newFixture(t, tc.files)
			err := Run(Options{ProjectPath: project, NoGraph: true})
			if err == nil {
				t.Fatal("expected an error")
			}
			if !strings.Contains(err.Error(), tc.wantErrPart) {
				t.Errorf("error = %v, want it to mention %q", err, tc.wantErrPart)
			}
		})
	}
}

// TestRunGeneratorErrors blocks one of the three summary artifacts with a
// directory of the same name and asserts the wrapped stage name.
func TestRunGeneratorErrors(t *testing.T) {
	cases := []struct {
		name        string
		blocker     string
		wantErrPart string
	}{
		{"project.json", "project.json", "generate project.json"},
		{"project.structure.json", "project.structure.json", "generate project.structure.json"},
		{"overview.md", "overview.md", "generate overview.md"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			captureLogs(t)
			project := newFixture(t, map[string]string{
				"go.mod":                               "module x\n",
				"main.go":                              "package main\n",
				".plaesy/analysis/" + tc.blocker + "/": "",
			})
			err := Run(Options{ProjectPath: project, NoGraph: true})
			if err == nil {
				t.Fatalf("expected an error when %s cannot be written", tc.blocker)
			}
			if !strings.Contains(err.Error(), tc.wantErrPart) {
				t.Errorf("error = %v, want it to mention %q", err, tc.wantErrPart)
			}
		})
	}
}

// TestRunRecordsFingerprintOnlyAfterGenerating: the fingerprint is the record of
// a *completed* analysis, so it is written after the generators succeed.
// shouldSkipAnalysis used to write it before they ran, which meant a failed run
// left a valid fingerprint behind: the next run took the skip path, printed
// "Analysis unchanged since last run" and listed project.json as "(cached)" while
// the file did not exist — a check reporting success for work it had not done.
func TestRunRecordsFingerprintOnlyAfterGenerating(t *testing.T) {
	project := newFixture(t, map[string]string{
		"go.mod":                         "module x\n",
		"main.go":                        "package main\n",
		".plaesy/analysis/project.json/": "", // blocks the first generation
	})
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err == nil {
		t.Fatal("expected the first run to fail while writing project.json")
	}

	// Unblock the writer. The failed run left no fingerprint behind, so this run
	// must regenerate rather than claim the analysis is cached.
	if err := os.RemoveAll(filepath.Join(project, filepath.FromSlash(analysisDirName), "project.json")); err != nil {
		t.Fatalf("remove blocker: %v", err)
	}
	logs := captureLogs(t)
	if err := Run(Options{ProjectPath: project, NoGraph: true}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(project, filepath.FromSlash(analysisDirName), "project.json")); err != nil {
		t.Fatalf("the second run must regenerate project.json: %v", err)
	}
	if out := logs.joined(); strings.Contains(out, "Skipping regeneration") {
		t.Errorf("a failed run must not leave a fingerprint that skips the next one:\n%s", out)
	}
}

// TestRunSkipPathListsGraphArtifactsWhenGraphIsEnabled covers the cached
// narration branch that only runs when the graph is not disabled.
func TestRunSkipPathListsGraphArtifactsWhenGraphIsEnabled(t *testing.T) {
	project := analysisFixture(t)
	if err := Run(Options{ProjectPath: project}); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	logs := captureLogs(t)
	if err := Run(Options{ProjectPath: project}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	out := logs.joined()
	mustContain(t, out, "Analysis unchanged since last run.")
	mustContain(t, out, "- project.graph.json - Dependency graph (cached)")
	mustContain(t, out, "- project.html - Interactive graph visualization (cached)")
	mustContain(t, out, "- reports.md - Graph report (cached)")
}

func TestDefaultLogFunctionsWritePrefixedLines(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}
	origStdout := os.Stdout
	os.Stdout = w
	func() {
		defer func() {
			os.Stdout = origStdout
			_ = w.Close()
		}()
		Logf("hello %s", "world")
		Successf("done %d", 7)
	}()
	data, err := io.ReadAll(r)
	if err != nil {
		t.Fatalf("read captured stdout: %v", err)
	}
	got := string(data)
	mustContain(t, got, "[INFO] hello world\n")
	mustContain(t, got, "[SUCCESS] done 7\n")
}
